default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: git-app_development

test:
  <<: *default
  database: git-app_test


production:
  <<: *default
  database: git-app_production
  username: git-app
  password: <%= ENV['GIT-APP_DATABASE_PASSWORD'] %>
